--- 
output_dir: output
text_extensions: [ 'css', 'erb', 'haml', 'htm', 'html', 'js', 'less', 'markdown', 'md', 'php', 'rb', 'sass', 'txt' ]
index_filenames: ["index.html"]
allow_periods_in_identifiers: false
data_sources: 
- items_root: /
  layouts_root: /
  type: filesystem_unified
